bits:
  - material: DIAMOND_BLOCK
    speed: 100
    durability: 100
    yield: 60
    replant: false
  - material: EMERALD_BLOCK
    speed: 80
    durability: 100
    yield: 60
    replant: true
  - material: GOLD_BLOCK
    speed: 60
    durability: 50
    yield: 100
    replant: false
obstacles:
  - DANDELION
  - POPPY
  - BLUE_ORCHID
  - ALLIUM
  - AZURE_BLUET
  - RED_TULIP
  - ORANGE_TULIP
  - WHITE_TULIP
  - PINK_TULIP
  - OXEYE_DAISY
  - CORNFLOWER
  - LILY_OF_THE_VALLEY
  - WITHER_ROSE
  - SUNFLOWER
  - LILAC
  - ROSE_BUSH
  - PEONY
  - BROWN_MUSHROOM
  - RED_MUSHROOM
  - FERN
invisible:
  - TALL_GRASS
  - GRASS
  - OAK_SAPLING
  - SPRUCE_SAPLING
  - BIRCH_SAPLING
  - JUNGLE_SAPLING
  - ACACIA_SAPLING
  - DARK_OAK_SAPLING
  - CHERRY_SAPLING